services:
  redis:
    image: redis:7-alpine
    container_name: smp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smp_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  min_io:
    image: minio/minio
    container_name: smp_minio
    env_file:
      - ./backend/.env
    environment:
      MINIO_SERVER_URL: "http://localhost:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      smp_network:
        aliases:
          - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio_setup:
    image: minio/mc:latest
    container_name: smp_minio_setup
    depends_on:
      min_io:
        condition: service_healthy
    volumes:
      - ./backend/setup-minio.sh:/setup-minio.sh
    networks:
      - smp_network
    entrypoint: /bin/bash
    command: /setup-minio.sh
    restart: "no"

  postgres:
    image: postgres:15-alpine
    container_name: smp_postgres
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smp_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      min_io:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/main.py:/app/main.py
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/migrations:/app/migrations
    networks:
      - smp_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smp_frontend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - smp_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  smp_network:
    driver: bridge
