"""add_trecho_new_fields

Revision ID: 871a69aff77d
Revises: 20260609_add_laudo_fields
Create Date: 2026-06-17 23:29:00.053391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871a69aff77d'
down_revision: Union[str, Sequence[str], None] = '20260609_add_laudo_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trechos', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('trechos', sa.Column('uf', sa.String(length=2), nullable=True))
    op.add_column('trechos', sa.Column('responsavel_tecnico', sa.String(length=150), nullable=True))
    op.add_column('trechos', sa.Column('classificacao_qualidade', sa.String(length=50), nullable=True))
    op.add_column('trechos', sa.Column('defeitos', sa.JSON(), nullable=True))
    op.add_column('trechos', sa.Column('responsavel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trechos', 'user', ['responsavel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trechos', type_='foreignkey')
    op.drop_column('trechos', 'responsavel_id')
    op.drop_column('trechos', 'defeitos')
    op.drop_column('trechos', 'classificacao_qualidade')
    op.drop_column('trechos', 'responsavel_tecnico')
    op.drop_column('trechos', 'uf')
    op.drop_column('trechos', 'cidade')
    # ### end Alembic commands ###
