"""Change colaborador FK to use supervisor id

Revision ID: c58fc16ff8df
Revises: 021ca0f0cb1c
Create Date: 2026-04-21 01:30:18.501624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58fc16ff8df'
down_revision: Union[str, Sequence[str], None] = '021ca0f0cb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborador')
    op.drop_table('supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('idendificador_profissional', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('uf', postgresql.ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='ufenum'), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tentativas_falhas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('limite_de_bloqueio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('supervisor_pkey')),
    sa.UniqueConstraint('email', name=op.f('supervisor_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('idendificador_profissional', name=op.f('supervisor_idendificador_profissional_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('colaborador',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('id_profissional_responsavel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uf', postgresql.ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='ufenum'), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('instituicao_ensino', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('empresa_ou_orgao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_tecnico', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('limite_acesso', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acesso_liberado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tentativas_falhas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('limite_de_bloqueio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_profissional_responsavel'], ['supervisor.id'], name=op.f('colaborador_id_profissional_responsavel_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('colaborador_pkey')),
    sa.UniqueConstraint('email', name=op.f('colaborador_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
