"""create_laudo_table

Revision ID: cebc224e0ced
Revises: 20260601_merge_prs_trch
Create Date: 2026-06-09 02:15:51.568353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebc224e0ced'
down_revision: Union[str, Sequence[str], None] = '20260601_merge_prs_trch'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laudo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laudo_id'), 'laudo', ['id'], unique=False)
    op.create_table('laudo_user',
    sa.Column('laudo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laudo_id'], ['laudo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('laudo_id', 'user_id')
    )
    op.alter_column('colaborador', 'senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('password_reset_token_token_hash_key'), 'password_reset_token', type_='unique')
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_token_token_hash_key'), 'password_reset_token', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('colaborador', 'senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('laudo_user')
    op.drop_index(op.f('ix_laudo_id'), table_name='laudo')
    op.drop_table('laudo')
    # ### end Alembic commands ###
